### ISSUE TITLE
website doesnt display properly

### ISSUE THREAD

**Issue by charlie-sans** [OpenStudioCorp/NewOpenStudioCorpSite#11]
so the size of the website pages doesnt scale correctly for some reason 

the main homepage requires to be zoomed in around 150% just to see the page correctly

hope this helps!

**Comment by Ex-ce-pt** [comment]
We're working on it. We develop for mobile first. Also we all work on different pages, so the pages might have different scales for now.

**Comment by charlie-sans** [comment]
fair, i also have to learn the new routing as it's been a while since i worked on this
