### ISSUE TITLE
redesign the whole site!

### ISSUE THREAD

**Issue by charlie-sans** [OpenStudioCorp/NewOpenStudioCorpSite#4]

**Comment by Ex-ce-pt** [comment]
I don't think it's an issue if it's the whole point of this project...

**Comment by charlie-sans** [comment]
and i guess we did it?

looks better then the old one ill tell you that

Ex-ce-pt for one thing, roles. lets add roles to the site under the team members page, as in have it like

[Sourena](https://github.com/sourena-kazemi)
Charlieeeee you cant copy that much html
front end dev

something like that?

**Comment by charlie-sans** [comment]
is the site done? because all ive seen is just me adding new keys to the openstudiocorpprojects.json file?

**Comment by charlie-sans** [comment]
> Reference in ne

do you think it's time to rewrite the Readme?
oh and rename the Repository to something like

OpenStudioCorp, or just OpenStudio?

**Comment by Diederick87** [comment]
Damn I am receiving so many mails now lol

**Comment by charlie-sans** [comment]
ahhahahha lol

**Comment by Diederick87** [comment]
Well I am glad the email function is working good

**Comment by charlie-sans** [comment]
with all responsibility comes an end. we have finished the site!!!!

now this doesn't mean that we wont have fixes for it and stuff, there's going to be a load of those probably forever.

thanks to everyone who has worked on this, for now though i'm going to have to close this with a comment.

if needed in the future, feel free to open this again for anything we have missed.

i'm going to allocate all the resources on this project to the CubeScript website built with the same techstack but having astro as the front end. Take care!
